// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QotD.Bot.Data;

#nullable disable

namespace QotD.Bot.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416105536_AddAutoModeration")]
    partial class AddAutoModeration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QotD.Bot.Data.Models.AutoModerationAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Evidence")
                        .HasMaxLength(1800)
                        .HasColumnType("character varying(1800)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "CreatedAtUtc");

                    b.HasIndex("GuildId", "RuleKey", "CreatedAtUtc");

                    b.HasIndex("GuildId", "UserId", "CreatedAtUtc");

                    b.ToTable("AutoModerationAuditEntries");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.AutoModerationConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnforceAccountAgeForLinks")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnforceServerAgeForLinks")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLockdownActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockdownActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockdownEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LockdownMinAccountAgeHours")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("MinAccountAgeDaysForLinks")
                        .HasColumnType("integer");

                    b.Property<int>("MinServerAgeHoursForLinks")
                        .HasColumnType("integer");

                    b.Property<int>("RaidJoinThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("RaidLockdownMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("RaidModeEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("RaidWindowSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("RestrictToVerifiedRoleDuringLockdown")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("VerifiedRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("LogChannelId");

                    b.ToTable("AutoModerationConfigs");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.AutoModerationRaidIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TriggerJoinCount")
                        .HasColumnType("integer");

                    b.Property<int>("WindowSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "EndedAtUtc");

                    b.HasIndex("GuildId", "StartedAtUtc");

                    b.ToTable("AutoModerationRaidIncidents");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.BirthdayConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("AnnouncementChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("BirthdayRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateOnly?>("LastAnnouncementDate")
                        .HasColumnType("date");

                    b.HasKey("GuildId");

                    b.ToTable("BirthdayConfigs");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.CountingChannelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Highscore")
                        .HasColumnType("integer");

                    b.Property<decimal>("LastUserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.ToTable("CountingChannels");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.GuildConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text");

                    b.Property<decimal?>("PingRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<TimeOnly>("PostTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.GuildHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("GuildId", "QuestionId")
                        .IsUnique();

                    b.ToTable("GuildHistories");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.LinkFilterBypassChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "ChannelId")
                        .IsUnique();

                    b.ToTable("LinkFilterBypassChannels");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.LinkFilterBypassRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "RoleId")
                        .IsUnique();

                    b.ToTable("LinkFilterBypassRoles");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.LinkFilterConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ChannelWarningTemplate")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DirectMessageTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<bool>("SendChannelWarning")
                        .HasColumnType("boolean");

                    b.Property<bool>("SendDirectMessageWarning")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.HasIndex("LogChannelId");

                    b.ToTable("LinkFilterConfigs");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.LinkFilterRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NormalizedDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "NormalizedDomain")
                        .IsUnique();

                    b.ToTable("LinkFilterRules");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.LogRoutingConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("LogType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LogRoutingConfigs");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Posted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("ScheduledFor")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledFor")
                        .IsUnique();

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.SelfRoleConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("AllowMultipleRoles")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ModerationChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("PanelChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("PanelColorHex")
                        .HasColumnType("text");

                    b.Property<string>("PanelDescriptionTemplate")
                        .HasColumnType("text");

                    b.Property<string>("PanelFooter")
                        .HasColumnType("text");

                    b.Property<string>("PanelImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("PanelMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("PanelThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("PanelTitle")
                        .HasColumnType("text");

                    b.Property<bool>("RequireModeration")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.HasIndex("ModerationChannelId");

                    b.HasIndex("PanelChannelId");

                    b.ToTable("SelfRoleConfigs");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.SelfRoleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsExclusive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "DisplayOrder");

                    b.HasIndex("GuildId", "Name")
                        .IsUnique();

                    b.ToTable("SelfRoleGroups");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.SelfRoleOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("EmojiKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("GuildId", "DisplayOrder");

                    b.HasIndex("GuildId", "EmojiKey")
                        .IsUnique();

                    b.HasIndex("GuildId", "RoleId")
                        .IsUnique();

                    b.ToTable("SelfRoleOptions");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.SelfRoleRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ModerationChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ModerationMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("PanelMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Status", "RequestedAtUtc");

                    b.HasIndex("GuildId", "UserId", "RoleId", "Status");

                    b.ToTable("SelfRoleRequests");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.TeamActivityPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MinMessagesPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("MinVoiceMinutesPerWeek")
                        .HasColumnType("integer");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "RoleId")
                        .IsUnique();

                    b.ToTable("TeamActivityPolicies");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.TeamActivityWeeklySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CombinedScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("MeetsMinimum")
                        .HasColumnType("boolean");

                    b.Property<int>("Messages")
                        .HasColumnType("integer");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("VoiceMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("WasExcused")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("WeekStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId");

                    b.HasIndex("GuildId", "WeekStartUtc");

                    b.HasIndex("GuildId", "WeekStartUtc", "RoleId", "UserId")
                        .IsUnique();

                    b.ToTable("TeamActivityWeeklySnapshots");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.TeamLeaveEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "EndUtc");

                    b.HasIndex("GuildId", "UserId", "StartUtc");

                    b.ToTable("TeamLeaveEntries");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.TeamListConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomFooter")
                        .HasColumnType("text");

                    b.Property<string>("CustomTemplate")
                        .HasColumnType("text");

                    b.Property<string>("CustomTitle")
                        .HasColumnType("text");

                    b.Property<decimal?>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.PrimitiveCollection<decimal[]>("TrackedRoles")
                        .IsRequired()
                        .HasColumnType("numeric(20,0)[]");

                    b.HasKey("GuildId");

                    b.ToTable("TeamListConfigs");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.TeamRoleChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("NewRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NewRoleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("OldRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("OldRoleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "ChangedAtUtc");

                    b.ToTable("TeamRoleChangeHistories");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.TeamWarning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreatedByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ResolvedByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("WarningType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("WeekStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "IsActive", "IsResolved");

                    b.HasIndex("GuildId", "WeekStartUtc", "UserId", "RoleId", "WarningType");

                    b.ToTable("TeamWarnings");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.TeamWarningNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AuthorUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("NoteType")
                        .HasColumnType("integer");

                    b.Property<int>("WarningId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WarningId");

                    b.HasIndex("GuildId", "WarningId", "CreatedAtUtc");

                    b.ToTable("TeamWarningNotes");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.TeamWeeklyReportConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastReportedWeekStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId");

                    b.HasIndex("ChannelId");

                    b.ToTable("TeamWeeklyReportConfigs");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.TempVoiceConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("CategoryId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("TriggerChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("TempVoiceConfigs");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.UserBirthday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MemberId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "GuildId")
                        .IsUnique();

                    b.ToTable("UserBirthdays");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.WordChainConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChainLength")
                        .HasColumnType("integer");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Highscore")
                        .HasColumnType("integer");

                    b.Property<decimal>("LastUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("LastWord")
                        .HasColumnType("text");

                    b.Property<string>("UsedWordsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.ToTable("WordChainConfigs");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.GuildHistory", b =>
                {
                    b.HasOne("QotD.Bot.Data.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.SelfRoleOption", b =>
                {
                    b.HasOne("QotD.Bot.Data.Models.SelfRoleGroup", "Group")
                        .WithMany("Options")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.TeamWarningNote", b =>
                {
                    b.HasOne("QotD.Bot.Data.Models.TeamWarning", "Warning")
                        .WithMany("Notes")
                        .HasForeignKey("WarningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warning");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.SelfRoleGroup", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("QotD.Bot.Data.Models.TeamWarning", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
